# Generated by Django 4.2.4 on 2023-08-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registrationmodel',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('bio', models.CharField(max_length=100)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
