# Generated by Django 4.2.4 on 2023-08-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
