# Generated by Django 4.2.4 on 2023-08-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_registrationmodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
