# Generated by Django 4.2.4 on 2023-08-10 05:02

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_registrationmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
