# Generated by Django 4.2.4 on 2023-08-11 05:06

from django.db import migrations, models
import phonenumber_field.modelfields



class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_registrationmodel_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adid', models.IntegerField()),
                ('ademail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='emplmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bio', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
