# Generated by Django 4.2.4 on 2023-08-11 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_adminmodel_emplmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminmodel',
            old_name='ademail',
            new_name='email',
        ),
    ]
