# Generated by Django 4.2.4 on 2023-08-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_ademail_adminmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplmodel',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
