# Generated by Django 4.2.4 on 2023-08-11 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_emplmodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be 10 digits long.', regex='^\\d{10}$')]),
        ),
    ]
