# Generated by Django 4.2.4 on 2023-08-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_employemodel_delete_emplmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registrationmodel',
        ),
    ]
