# Generated by Django 4.2.4 on 2023-08-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_registrationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrationmodel',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField()),
                ('bio', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
    ]
