# Generated by Django 4.2.3 on 2023-08-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_registrationmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationmodel',
            name='photo',
        ),
    ]
