# Generated by Django 4.2.4 on 2023-08-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_registrationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='bio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
