# Generated by Django 4.2.4 on 2023-08-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_registrationmodel_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='slotmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField(max_length=100)),
                ('stphoto', models.CharField(max_length=100)),
                ('stdeteals', models.CharField(max_length=500)),
            ],
        ),
    ]
