# Generated by Django 4.2.3 on 2023-08-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_registrationmodel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmodel',
            name='photo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
