# Generated by Django 4.2.3 on 2023-08-29 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_registrationmodel_photo'),
        ('app', '0013_slotmodel'),
    ]

    operations = [
    ]
