# Generated by Django 4.2.3 on 2023-08-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_merge_0013_registrationmodel_photo_0013_slotmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='slotmodel',
            name='stphoto',
            field=models.FileField(upload_to=''),
        ),
    ]
