# Generated by Django 4.2.3 on 2023-09-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='data',
        ),
    ]
