# Generated by Django 4.2.3 on 2023-09-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_date_appointment_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='customerdetails',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='data',
            field=models.CharField(max_length=30),
        ),
    ]
