# Generated by Django 4.2.3 on 2023-09-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_appointment_customerdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='employee',
            field=models.CharField(max_length=30),
        ),
    ]
