# Generated by Django 4.2.3 on 2023-09-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_appointment_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='customerdetails',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='data',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='employee',
            field=models.CharField(max_length=80),
        ),
    ]
