# Generated by Django 4.2.3 on 2023-09-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_slotmodel_stphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotmodel',
            name='stphoto',
        ),
    ]
