# Generated by Django 4.2.3 on 2023-09-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_slotmodel_stphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='raiseslotmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField(max_length=100)),
                ('stdeteals', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='slotmodel',
            name='stphoto',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
