# Generated by Django 4.2.3 on 2023-09-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_raiseslotmodel_slotmodel_stphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='raiseslotmodel',
        ),
    ]
