# Generated by Django 4.2.3 on 2023-09-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_delete_raiseslotmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='raiseslotmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('stdeteals', models.CharField(max_length=500)),
            ],
        ),
    ]
