# Generated by Django 4.2.3 on 2023-09-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_raiseslotmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
