# Generated by Django 4.2.3 on 2023-09-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=80)),
                ('data', models.CharField(max_length=80)),
                ('customerdetails', models.CharField(max_length=80)),
                ('customerphoto', models.FileField(upload_to='')),
            ],
        ),
    ]
