# Generated by Django 4.2.3 on 2023-09-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='customerphoto',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
