# Generated by Django 4.2.3 on 2023-09-06 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_appointment_customerphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='customerphoto',
        ),
    ]
