# Generated by Django 4.2.3 on 2023-09-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_appointment_customerphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='customerphoto',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
