# Generated by Django 4.2.3 on 2023-09-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_appointment_customerphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='raiseslotmodel',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='customerphoto',
        ),
    ]
