# Generated by Django 4.2.3 on 2023-09-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_raiseslotmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slotmodel',
        ),
    ]
