# Generated by Django 4.2.3 on 2023-09-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_delete_slotmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='slotmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField(max_length=100)),
                ('stphoto', models.FileField(upload_to='')),
                ('stphoto2', models.FileField(upload_to='')),
                ('stphoto3', models.FileField(upload_to='')),
                ('stdeteals', models.CharField(max_length=500)),
            ],
        ),
    ]
