# Generated by Django 4.2.3 on 2023-09-07 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_slotmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employemodel',
        ),
    ]
