# Generated by Django 4.2.3 on 2023-09-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_delete_employemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='employemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bio', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('locatioon', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
