# Generated by Django 4.2.3 on 2023-09-07 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_employemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employemodel',
            old_name='locatioon',
            new_name='city',
        ),
    ]
