# Generated by Django 4.2.3 on 2023-09-07 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_rename_locatioon_employemodel_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='raiseslotmodel',
        ),
    ]
