# Generated by Django 4.2.3 on 2023-09-07 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_raiseslotmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='raiseslotmodel',
        ),
    ]
