# Generated by Django 4.2.3 on 2023-09-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_delete_raiseslotmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='raiseslotmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('userphoto', models.FileField(null=True, upload_to='')),
                ('stdeteals', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=30)),
                ('splocation', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
