# Generated by Django 4.2.3 on 2023-09-10 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_raiseslotmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employemodel',
        ),
    ]
