# Generated by Django 5.0.7 on 2024-07-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_registrationmodel_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registrationmodel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
