# Generated by Django 5.0.7 on 2024-07-12 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_registrationmodel_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employemodel',
        ),
    ]
