# Generated by Django 5.0.7 on 2024-07-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_delete_employemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='employemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bio', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('photo1', models.FileField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('rate', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
