# Generated by Django 5.0.7 on 2024-07-13 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_employemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
