# Generated by Django 5.0.7 on 2024-07-13 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=80)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registrationmodel')),
            ],
        ),
    ]
