# Generated by Django 5.0.7 on 2024-07-13 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
