# Generated by Django 5.0.7 on 2024-07-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employemodel',
            name='activation',
            field=models.BooleanField(default=False),
        ),
    ]
