# Generated by Django 5.0.7 on 2024-07-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_employemodel_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='activation',
            field=models.BooleanField(default=False),
        ),
    ]
